// SPDX-License-Identifier: AGPL-3.0-only

package blueprintschema

import (
	_ "embed"
	"encoding/json"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// fielddocs.json is the generated index of field descriptions (Go doc comments) keyed by
// "<importPath>.<TypeName>.<FieldName>". It is embedded so the running binary needs no source
// (the control-plane UI serves descriptions from here). Regenerated by `make blueprint-schema`;
// the TestSchemaCurrent gate fails if it drifts from the live doc comments.
//
//go:embed fielddocs.json
var embeddedDocsJSON []byte

// EmbeddedDocs returns the embedded field-description index.
func EmbeddedDocs() docLookup {
	var m map[string]string
	if len(embeddedDocsJSON) == 0 {
		return docLookup{}
	}
	_ = json.Unmarshal(embeddedDocsJSON, &m)
	return docLookup(m)
}

// FindModuleRoot walks up from start until it finds the dir containing go.mod.
func FindModuleRoot(start string) (string, error) {
	dir := start
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}

// schemaSourceDirs are the package directories (module-relative) whose struct doc comments
// feed the schema: the blueprint surface + every construct/workload Config.
func schemaSourceDirs(moduleRoot string) ([]string, error) {
	var dirs []string
	dirs = append(dirs, filepath.Join(moduleRoot, "internal", "blueprint"))
	for _, glob := range []string{
		filepath.Join(moduleRoot, "internal", "construct", "*"),
		filepath.Join(moduleRoot, "internal", "workload", "*"),
	} {
		matches, err := filepath.Glob(glob)
		if err != nil {
			return nil, err
		}
		for _, m := range matches {
			if fi, err := os.Stat(m); err == nil && fi.IsDir() {
				dirs = append(dirs, m)
			}
		}
	}
	return dirs, nil
}

// ExtractDocs parses the schema source dirs and returns a field-description index keyed by
// "<importPath>.<TypeName>.<FieldName>". Used at generate/gate time only (needs source).
func ExtractDocs(moduleRoot string) (map[string]string, error) {
	dirs, err := schemaSourceDirs(moduleRoot)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, dir := range dirs {
		importPath, err := filepath.Rel(moduleRoot, dir)
		if err != nil {
			return nil, err
		}
		importPath = "github.com/rknightion/synthkit/" + filepath.ToSlash(importPath)
		fset := token.NewFileSet()
		pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
			return !strings.HasSuffix(fi.Name(), "_test.go")
		}, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		for _, pkg := range pkgs {
			collectStructDocs(pkg, importPath, out)
		}
	}
	return out, nil
}

// collectStructDocs walks every struct type in pkg, recording each field's doc comment.
func collectStructDocs(pkg *ast.Package, importPath string, out map[string]string) {
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok || st.Fields == nil {
					continue
				}
				for _, field := range st.Fields.List {
					doc := fieldDoc(field)
					if doc == "" {
						continue
					}
					for _, name := range field.Names {
						out[importPath+"."+ts.Name.Name+"."+name.Name] = doc
					}
				}
			}
		}
	}
}

// fieldDoc prefers the doc comment above a field, falling back to the trailing line comment.
func fieldDoc(field *ast.Field) string {
	if field.Doc != nil {
		return cleanDoc(field.Doc.Text())
	}
	if field.Comment != nil {
		return cleanDoc(field.Comment.Text())
	}
	return ""
}

// cleanDoc collapses a multi-line comment into a single trimmed line.
func cleanDoc(s string) string {
	s = strings.TrimSpace(s)
	fields := strings.Fields(strings.ReplaceAll(s, "\n", " "))
	return strings.Join(fields, " ")
}
