// Vendored from github.com/grafana/pyroscope api/push/v1/push.proto.
// Transformations applied:
//   - gnostic/openapi import and all (gnostic.openapi.v3.*) field options stripped
//   - LabelPair message co-located from api/types/v1/types.proto (field numbers unchanged)
//   - types.v1.LabelPair references resolved to local LabelPair
//   - annotations field (field 3) on RawProfileSeries dropped; field number 3 is reserved
//   - service PusherService dropped (we hand-POST; no generated client needed)
//   - option go_package set to synthkit path
// Field numbers and wire contract for retained fields are identical to upstream.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: push.proto

package pushv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LabelPair is a key/value label that identifies a Pyroscope series.
// Co-located from api/types/v1/types.proto — field numbers unchanged.
type LabelPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Label name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Label value
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelPair) Reset() {
	*x = LabelPair{}
	mi := &file_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelPair) ProtoMessage() {}

func (x *LabelPair) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelPair.ProtoReflect.Descriptor instead.
func (*LabelPair) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

func (x *LabelPair) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// WriteRawRequest writes a pprof profile
type PushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series is a set of raw pprof profiles and accompanying labels
	Series        []*RawProfileSeries `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushRequest) GetSeries() []*RawProfileSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

// RawProfileSeries represents the pprof profile and its associated labels
type RawProfileSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels are the key/value pairs to identify the corresponding profile
	Labels []*LabelPair `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	// samples are the set of profile bytes
	Samples       []*RawSample `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawProfileSeries) Reset() {
	*x = RawProfileSeries{}
	mi := &file_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawProfileSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProfileSeries) ProtoMessage() {}

func (x *RawProfileSeries) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawProfileSeries.ProtoReflect.Descriptor instead.
func (*RawProfileSeries) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{2}
}

func (x *RawProfileSeries) GetLabels() []*LabelPair {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RawProfileSeries) GetSamples() []*RawSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// RawSample is the set of bytes that correspond to a pprof profile
type RawSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw_profile is the set of bytes of the pprof profile
	RawProfile []byte `protobuf:"bytes,1,opt,name=raw_profile,json=rawProfile,proto3" json:"raw_profile,omitempty"`
	// UUID of the profile
	ID            string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawSample) Reset() {
	*x = RawSample{}
	mi := &file_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawSample) ProtoMessage() {}

func (x *RawSample) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawSample.ProtoReflect.Descriptor instead.
func (*RawSample) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{3}
}

func (x *RawSample) GetRawProfile() []byte {
	if x != nil {
		return x.RawProfile
	}
	return nil
}

func (x *RawSample) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_push_proto protoreflect.FileDescriptor

const file_push_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"push.proto\x12\apush.v1\"5\n" +
	"\tLabelPair\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"@\n" +
	"\vPushRequest\x121\n" +
	"\x06series\x18\x01 \x03(\v2\x19.push.v1.RawProfileSeriesR\x06series\"r\n" +
	"\x10RawProfileSeries\x12*\n" +
	"\x06labels\x18\x01 \x03(\v2\x12.push.v1.LabelPairR\x06labels\x12,\n" +
	"\asamples\x18\x02 \x03(\v2\x12.push.v1.RawSampleR\asamplesJ\x04\b\x03\x10\x04\"<\n" +
	"\tRawSample\x12\x1f\n" +
	"\vraw_profile\x18\x01 \x01(\fR\n" +
	"rawProfile\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02IDB0Z.synthkit/internal/sink/pyroscope/pushv1;pushv1b\x06proto3"

var (
	file_push_proto_rawDescOnce sync.Once
	file_push_proto_rawDescData []byte
)

func file_push_proto_rawDescGZIP() []byte {
	file_push_proto_rawDescOnce.Do(func() {
		file_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)))
	})
	return file_push_proto_rawDescData
}

var file_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_push_proto_goTypes = []any{
	(*LabelPair)(nil),        // 0: push.v1.LabelPair
	(*PushRequest)(nil),      // 1: push.v1.PushRequest
	(*RawProfileSeries)(nil), // 2: push.v1.RawProfileSeries
	(*RawSample)(nil),        // 3: push.v1.RawSample
}
var file_push_proto_depIdxs = []int32{
	2, // 0: push.v1.PushRequest.series:type_name -> push.v1.RawProfileSeries
	0, // 1: push.v1.RawProfileSeries.labels:type_name -> push.v1.LabelPair
	3, // 2: push.v1.RawProfileSeries.samples:type_name -> push.v1.RawSample
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_push_proto_init() }
func file_push_proto_init() {
	if File_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_proto_goTypes,
		DependencyIndexes: file_push_proto_depIdxs,
		MessageInfos:      file_push_proto_msgTypes,
	}.Build()
	File_push_proto = out.File
	file_push_proto_goTypes = nil
	file_push_proto_depIdxs = nil
}
