// SPDX-License-Identifier: AGPL-3.0-only

// Package app implements the v1 "app" workload (Spec 5): a blueprint-declared service GRAPH of
// first-class, typed service nodes, each emitting its own request-correlated spans + logs and its
// own scraped metrics via the custom-telemetry DSL (internal/telemetryspec). ONE request-flow
// workload mints invocations at the entry node and projects ONE trace across the whole graph (the
// single-trace-many-hops mechanism, preserved — a node is NOT its own core.Workload; the runner
// dispatches by the single string req.Workload).
//
// Kind: "app"  (coexists with — does NOT replace — "web_service": the simple single-service kind).
// Signals: Metrics + Traces + Logs.
// Interval: 60s (metric lane; the DPM floor — I10).
//
// Realism lives in the NAMES (real metric/label/field names, sourced from signals/, via the DSL);
// genericity lives in the ARCHITECTURE (all service identity/topology/shapes are blueprint-declared,
// zero customer tokens here). NO OTel SDK: metrics via promrw final names, spans via the
// hand-encoded OTLP seam, logs via Loki — the same hard rule as web_service.
package app

import (
	"time"

	"github.com/rknightion/synthkit/internal/core"
	"github.com/rknightion/synthkit/internal/failuremode"
	"github.com/rknightion/synthkit/internal/fixture"
	"github.com/rknightion/synthkit/internal/ledger"
	"github.com/rknightion/synthkit/internal/pyroscope"
	"github.com/rknightion/synthkit/internal/state"
	"github.com/rknightion/synthkit/internal/telemetryspec"
)

const (
	kind     = "app"
	interval = 60 * time.Second

	// serviceVersion is the default semver stamped on service.version when a node declares no override.
	serviceVersion = "1.0.0"
)

// versionOr returns the node's declared version override, or the serviceVersion default when empty.
func versionOr(v string) string {
	if v == "" {
		return serviceVersion
	}
	return v
}

// Config is the YAML config for the app workload: a service graph + an entry traffic envelope.
// Unknown fields are rejected by strict yaml.v3 decoding at blueprint load.
type Config struct {
	// Services are the graph's nodes (typed services + their call edges).
	Services []ServiceNode `yaml:"services"`
	// Traffic shapes the entry node's invocation volume (the correlated narrative sample).
	Traffic Traffic `yaml:"traffic"`

	// Models is the set of valid (model, provider) routings this app's requests draw from. The minter
	// picks ONE pair per request and stamps it into the correlation, so the gen_ai spans + gateway
	// export logs of every gen_ai-composed node carry the REAL model AND provider (the names-are-law
	// value behind the gen_ai_client / gateway_export_log profiles). Pairing them (vs two independent
	// lists) prevents impossible combinations like a Claude model on the Azure-OpenAI provider. Empty
	// ⇒ a non-AI app. These feed body/attr FIELDS only (never labels), so the per-request draw does
	// not affect the -dump inventory (I32). Values are blueprint-declared (customer model lists stay
	// out of the catalog).
	Models []ModelChoice `yaml:"models"`
}

// ModelChoice is one valid (model, provider) routing — paired so a request never draws an impossible
// combination. The app minter draws one ModelChoice per request → ledger.Request.Model/Provider.
type ModelChoice struct {
	Model    string `yaml:"model"`    // gen_ai.request.model (e.g. gpt-4o, claude-3.5-sonnet)
	Provider string `yaml:"provider"` // gen_ai.provider.name (e.g. azure-openai, bedrock)
}

// AgenticFlow declares the in-process LangChain/LangGraph orchestration shape a node runs per request.
// When set on a node, the app workload emits a NESTED gen_ai-semconv span subtree INSIDE that node's
// SERVER span (same service.name — orchestration is in-process, not separate services): one
// invoke_workflow span → one invoke_agent span (an agent drawn from Agents per request) → a
// deterministic subset of that agent's execute_tool spans → a chat <model> leaf (the LLM call), UNLESS
// OmitChat is set. The matching traces_spanmetrics_* + service-graph series can be generated by a
// Grafana Cloud metrics-generator FROM these emitted spans (span_name/span_kind dimensions) when a
// blueprint is not opted into synthkit's own span-metric emission — so span-name-scoped dashboards
// populate without synthkit fabricating them. gen_ai vocab + span names come from internal/genai (semconv-validated);
// content keys are never stamped.
type AgenticFlow struct {
	// Workflow is the LangGraph graph name → span "invoke_workflow <Workflow>" (gen_ai.workflow.name).
	Workflow string `yaml:"workflow"`
	// Agents is the pool of agents the workflow can invoke; one fires per request (deterministic draw).
	Agents []AgentDecl `yaml:"agents"`
	// OmitChat drops the chat <model> leaf — set where a CONNECTED gateway/llm hop already models the
	// LLM call (WS2/WS3 Path-B gateway span) so the LLM hop is not double-counted. WS1 (API-poll, no
	// connected gateway) leaves it false: the in-process chat span IS the observed LLM call.
	OmitChat bool `yaml:"omit_chat"`
}

// AgentDecl is one declarable agent in an AgenticFlow: a name (→ "invoke_agent <Name>",
// gen_ai.agent.name) and a pool of tools it may call (→ "execute_tool <tool>", gen_ai.tool.name).
type AgentDecl struct {
	Name  string   `yaml:"name"`
	Tools []string `yaml:"tools"`
}

// PageDecl is one browser-side page/view in a RUM navigation inventory (frontend entry nodes only).
// Page-views are RUM-ONLY: they model the session navigation a user does AROUND the traced action
// (load dashboard → browse library → open editor …) and emit NO backend trace and NO gen_ai — so
// enriching the FEO session view never inflates the backend's gen_ai request/token/cost metrics.
// This is distinct from `routes:`, which ARE the backend-calling (traced end-to-end) actions.
// Page/view/action NAMES live in the blueprint (the app-specific identity layer), never the catalog
// (three-tier rule) — the workload consumes them generically.
type PageDecl struct {
	Path    string   `yaml:"path"`    // SPA route → page_id / view_name / page_url (e.g. /document-library)
	Name    string   `yaml:"name"`    // human view name (e.g. "Document Library")
	Actions []string `yaml:"actions"` // slash-free user-action intents on this page (e.g. ["search documents","open document"])
}

// ServiceNode is one node of the service graph: a first-class backend service with composable
// (catalog profile) and/or inline (DSL) telemetry, its own replica scale bounds, and its call
// edges. Node names are UNIQUE within the graph — the node identity is auto-stamped on every
// emitted series/stream/span (so two nodes sharing a profile never collide; B3).
type ServiceNode struct {
	Name    string `yaml:"name"`    // unique graph identity (service / service_name label)
	Type    string `yaml:"type"`    // span semantics + profile fit (registry + default fallback)
	Runtime string `yaml:"runtime"` // go|jvm|node|python (informational; selects runtime profile)
	Entry   bool   `yaml:"entry"`   // the request entry point (mints invocations)
	// Namespace is the k8s namespace for this service. Default (empty) = node name (one namespace per
	// service, the historic default). When set, the namespace propagates to BOTH the k8s substrate
	// placement (fixture.Workload.Namespace → kube_pod_* kube_deployment_* namespace label) AND the
	// app workload's own emitted telemetry (namespace / k8s_namespace_name metric labels,
	// service.namespace / k8s.namespace.name OTLP resource attrs, Loki namespace stream label). This
	// keeps the two signal families consistent — a real OTel-instrumented pod in namespace "datagen"
	// emits k8s.namespace.name=datagen in both its kube-state-metrics AND its OTel resource block.
	Namespace string `yaml:"namespace"` // k8s namespace; default = node name
	// Context / UseCase / Team are the §5 resource-attr canon (optional; AI blueprints only).
	// Empty ⇒ OMITTED (I13). Context ∈ {Platform, ContentGen, DataGen}; Team is set per blueprint (blueprint-only identity).
	// Emitted as bounded metric labels (context/use_case) + resource attrs (context/use_case/team).
	Context string `yaml:"context"`
	UseCase string `yaml:"use_case"`
	Team    string `yaml:"team"`
	// Version overrides the default service.version (the released image-tag intent, §5). Empty ⇒ the
	// serviceVersion default. Stamped on service.version (resource attr) + service_version (spanmetrics).
	Version  string                     `yaml:"version"`
	Routes   []string                   `yaml:"routes"`   // request routes "{METHOD} {path}"; on the entry → drawn per request into r.Route (default "GET /"), on a callee → names its SERVER span (else the node name)
	Replicas int                        `yaml:"replicas"` // pods for the node cascade (default 2); per-node scaling §6.6
	Profiles []string                   `yaml:"profiles"` // catalog profile-template names (resolved at load)
	Metrics  []telemetryspec.MetricSpec `yaml:"metrics"`  // inline custom metrics (the DSL escape hatch)
	Logs     []telemetryspec.LogSpec    `yaml:"logs"`     // inline custom log streams
	Spans    []telemetryspec.SpanSpec   `yaml:"spans"`    // inline custom spans (extra attrs on this node's span)
	Calls    []string                   `yaml:"calls"`    // downstream node names (the graph edges / propagation)
	// DBInstance (db/cache leaf nodes only) names the BASE blueprint database this node represents
	// (e.g. "orders-pg"); the workload resolves it per-env against the binding's Databases to the
	// concrete RDS instance "<db_instance>-<lower(env)>" (case-insensitive env suffix; exact name
	// is the primary match). The resolved RDS identity decorates this node's db-CLIENT span
	// (db.system.name / db.namespace / server.address) so the trace links to the env's RDS instance
	// — faithful to real OTel/Beyla DB instrumentation. Empty ⇒ the leaf carries no DB identity
	// (back-compatible: the edge stays the bare node name).
	DBInstance  string                  `yaml:"db_instance"`
	Pages       []PageDecl              `yaml:"pages"`        // RUM navigation inventory (frontend entry only; empty ⇒ single-page behavior). RUM-only page-views, never backend-traced.
	External    bool                    `yaml:"external"`     // remote/managed service in another team's estate (e.g. a SaaS gateway): still appears as a connected span/hop in the trace, but is NOT placed as a k8s deployment on the caller's cluster
	AgenticFlow *AgenticFlow            `yaml:"agentic_flow"` // in-process LangGraph orchestration → nested gen_ai span subtree (invoke_workflow→invoke_agent→execute_tool*→chat) on this node's SERVER span; nil = no agentic flow
	Pyroscope   *pyroscope.ProfilingCfg `yaml:"pyroscope"`    // per-node Pyroscope SDK-push profiling (nil = disabled)
	// Resources optionally pins this service's container CPU/memory requests/limits + cAdvisor usage
	// base on the cluster (kube_pod_container_resource_*). nil ⇒ the k8scluster construct's
	// deterministic per-workload size-class defaults apply (back-compatible). It is a placement fact:
	// the blueprint resolver copies it onto fixture.Workload.Resources, so the value only affects the
	// k8s substrate lane, never this workload's own emitted telemetry.
	Resources *fixture.WorkloadResources `yaml:"resources"`
	// Controller/HasHPA/VolumeClaims are placement facts (like Resources): the blueprint resolver
	// copies them onto fixture.Workload so this node is modelled as the right k8s controller kind
	// (Deployment default | StatefulSet) with optional HPA/PVC. They affect ONLY the k8s substrate
	// lane (KSM family, pod naming, PVC/HPA), never this workload's own emitted telemetry.
	// `controller: daemonset` is rejected on an app service node at resolve time (DaemonSets don't
	// emit app traces — spec Q4); declare a DaemonSet via a `runs_in_cluster` integration instead.
	Controller   string   `yaml:"controller"`    // ""(⇒deployment) | statefulset
	HasHPA       bool     `yaml:"hpa"`           // opt-in kube_horizontalpodautoscaler_* (Deployment/StatefulSet)
	VolumeClaims []string `yaml:"volume_claims"` // PVC template names → kube_persistentvolumeclaim_*/kubelet_volume_stats_*/pv cost
}

// Traffic is the shape-driven entry-invocation envelope (mirrors web_service.Traffic).
type Traffic struct {
	Shape      string  `yaml:"shape"`        // shape profile name (informational)
	OffPeakRPS float64 `yaml:"off_peak_rps"` // trough rate (default 5)
	PeakRPS    float64 `yaml:"peak_rps"`     // plateau rate (default 50)
	// RequestLatencyP95Ms is the entry request's base end-to-end latency p95 (lognormal; the per-hop
	// budget + agentflow span windows derive from it). Default 0 ⇒ 200ms (plain HTTP). LLM/agentic
	// apps should set this to seconds (e.g. 9000) so http_server_request_duration + the in-process
	// invoke_workflow/agent/chat span latencies reflect real LLM-wait time, not HTTP speed.
	RequestLatencyP95Ms float64 `yaml:"request_latency_p95_ms"`
}

// NewConfig returns a *Config with documented defaults. An app MUST declare services (no default
// graph — unlike web_service's default endpoint).
func NewConfig() any {
	return &Config{Traffic: Traffic{OffPeakRPS: 5, PeakRPS: 50}}
}

// FailureModes are the modes app service nodes respond to, all on AxisService (per-node targeting,
// §6.5). The DSL `shape` value model reads the active mode for a node so any declared value built
// on `shape` is incident-responsive; the entry minter's per-request draws scope to the node too.
var FailureModes = []failuremode.Mode{
	{Name: "latency_storm", Axis: failuremode.AxisService, Help: "elevated request latency on the targeted service node"},
	{Name: "error_spike", Axis: failuremode.AxisService, Help: "elevated 5xx error rate on the targeted service node"},
	{Name: "throughput_drop", Axis: failuremode.AxisService, Help: "reduced throughput on the targeted service node"},
	{Name: "fallback_storm", Axis: failuremode.AxisService, Help: "elevated gateway fallback rate on the targeted service node"},
	{Name: "retry_storm", Axis: failuremode.AxisService, Help: "elevated gateway retry rate on the targeted service node"},
	// Profiling failure modes — drive incident-responsive flamegraph amplification in tickProfiles.
	// All on AxisService so each graph node can be targeted independently.
	{Name: "cpu_hotspot", Axis: failuremode.AxisService, Help: "elevated CPU concentrated in a hot frame on the targeted service node"},
	{Name: "memory_leak", Axis: failuremode.AxisService, Help: "growing heap on the targeted service node — raises memory inuse/alloc profile values"},
	{Name: "lock_contention", Axis: failuremode.AxisService, Help: "elevated mutex/block contention on the targeted service node"},
	{Name: "goroutine_leak", Axis: failuremode.AxisService, Help: "goroutine accumulation on the targeted service node"},
	{Name: "web_vitals_degraded", Axis: failuremode.AxisService, Help: "browser web-vitals degrade on the targeted frontend node — LCP/INP/TTFB/FCP and CLS spike"},
}

// Registration returns the core.WorkloadReg for the "app" kind. Call this from the composition
// root's catalog wiring file; no init() self-registration.
func Registration() core.WorkloadReg {
	return core.WorkloadReg{
		Kind:         kind,
		Doc:          "app — blueprint-declared service GRAPH; each node emits custom (DSL) metrics/logs/spans, one correlated trace across the graph",
		NewConfig:    NewConfig,
		Build:        build,
		FailureModes: FailureModes,
	}
}

// Workload is one app instance: a resolved service graph bound to a cluster/env.
type Workload struct {
	cfg Config
	b   core.Binding

	// resolved identity, frozen at Build from the binding.
	cluster string
	env     string
	weight  float64
	nonProd bool

	graph *graph       // validated graph (nodes + edges + effective specs)
	m     *minter      // entry-node invocation minter
	st    *state.State // cumulative metric state
}

// build constructs a Workload: decode-time defaults, resolve + validate the graph, freeze identity.
func build(cfgAny any, b core.Binding) (core.Workload, error) {
	cfg, _ := cfgAny.(*Config)
	if cfg == nil {
		cfg = NewConfig().(*Config)
	}
	if cfg.Traffic.PeakRPS <= 0 {
		cfg.Traffic.PeakRPS = 50
	}
	if cfg.Traffic.OffPeakRPS < 0 {
		cfg.Traffic.OffPeakRPS = 0
	}
	g, err := buildGraph(cfg.Services)
	if err != nil {
		return nil, err
	}
	w := &Workload{cfg: *cfg, b: b, graph: g, st: state.NewState()}
	w.resolveIdentity()
	// Wire each db/cache leaf that declared db_instance to its env's RDS/cache fixture (the resolver
	// owns the per-env identity; the workload only reads it from the binding — no minting).
	if err := g.resolveDBIdentities(w.env, b.Databases); err != nil {
		return nil, err
	}
	w.m = newMinter(w.b.Name, w.env, w.cluster, w.weight, w.nonProd, cfg.Traffic, cfg.Models, g)
	// Wire BrowserOrigin minting: the minter sets r.BrowserOrigin only when RUM is active
	// (entry has rum_faro + binding carries a Faro sink). Mirror webservice minter's cfg.RUM flag.
	w.m.rumEnabled = w.rumEnabled()
	return w, nil
}

// resolveIdentity pins cluster/env/weight from the binding once. Absent dimensions are OMITTED
// downstream — never sentinelled (I13).
func (w *Workload) resolveIdentity() {
	if w.b.Env != nil {
		w.env = w.b.Env.Name
		w.weight = w.b.Env.Weight
		w.nonProd = w.b.Env.NonProd
	}
	if w.weight == 0 {
		w.weight = 1.0
	}
	if w.b.Cluster != nil {
		w.cluster = w.b.Cluster.Name
	}
}

// Kind implements core.Workload.
func (w *Workload) Kind() string { return kind }

// Name implements core.Workload.
func (w *Workload) Name() string { return w.b.Name }

// Signals declares the classes this instance emits (Metrics + Traces + Logs; RUM is appended
// when rumEnabled; PyroscopeProfiles is appended when at least one node declares pyroscope in
// sdk mode — scraped mode is handled by Alloy, no push sink).
func (w *Workload) Signals() []core.SignalClass {
	sigs := []core.SignalClass{core.Metrics, core.Traces, core.Logs}
	if w.rumEnabled() {
		sigs = append(sigs, core.RUM)
	}
	for _, svc := range w.cfg.Services {
		if svc.Pyroscope != nil && svc.Pyroscope.Enabled && svc.Pyroscope.ModeOrDefault() != "scraped" {
			sigs = append(sigs, core.PyroscopeProfiles)
			break
		}
	}
	return sigs
}

// rumEnabled reports whether the Faro/RUM beacon lane is active for this workload. True when:
//   - the binding carries a Faro sink (b.RUM != nil), AND
//   - the entry node is a frontend type carrying the rum_faro catalog profile.
//
// Mirrors webservice.rumEnabled (cfg.RUM && b.RUM != nil) adapted to the app graph:
// instead of a config flag, the rum_faro profile on the entry node is the emission switch.
func (w *Workload) rumEnabled() bool {
	if w.b.RUM == nil {
		return false
	}
	return w.graph.entryHasRumFaro()
}

// Interval implements core.Workload (metric lane cadence).
func (w *Workload) Interval() time.Duration { return interval }

// Minter implements core.Workload.
func (w *Workload) Minter() ledger.Minter { return w.m }
