// SPDX-License-Identifier: AGPL-3.0-only

package k8scluster

// Captured target-family keys from reality-corpus/k8s/k3d-lab-otel-collector-prom.json.
// Scrape-health families are deliberately outside this projection.
var collectorPromLabels = map[string]string{
	"container_cpu_cfs_periods_total":                  "cluster container id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_cpu_cfs_throttled_periods_total":        "cluster container id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_cpu_usage_seconds_total":                "cluster container cpu id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_fs_reads_bytes_total":                   "cluster container device id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_fs_reads_total":                         "cluster container device id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_fs_writes_bytes_total":                  "cluster container device id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_fs_writes_total":                        "cluster container device id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_memory_cache":                           "cluster container id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_memory_rss":                             "cluster container id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_memory_swap":                            "cluster container id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_memory_working_set_bytes":               "cluster container id image instance job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_network_receive_bytes_total":            "cluster id image instance interface job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_network_receive_packets_dropped_total":  "cluster id image instance interface job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_network_receive_packets_total":          "cluster id image instance interface job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_network_transmit_bytes_total":           "cluster id image instance interface job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_network_transmit_packets_dropped_total": "cluster id image instance interface job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"container_network_transmit_packets_total":         "cluster id image instance interface job k8s_cluster_name name namespace otel_scope_name otel_scope_version pod",
	"go_goroutines":                                    "cluster instance job k8s_cluster_name otel_scope_name otel_scope_version",
	"kube_configmap_info":                              "cluster configmap instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_configmap_metadata_resource_version":         "cluster configmap instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_created":                           "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_metadata_generation":               "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_current_number_scheduled":   "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_desired_number_scheduled":   "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_number_available":           "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_number_misscheduled":        "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_number_ready":               "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_number_unavailable":         "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_observed_generation":        "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_daemonset_status_updated_number_scheduled":   "cluster daemonset instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_deployment_metadata_generation":              "cluster deployment instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_deployment_spec_replicas":                    "cluster deployment instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_deployment_status_condition":                 "cluster condition deployment instance job k8s_cluster_name namespace otel_scope_name otel_scope_version reason status",
	"kube_deployment_status_observed_generation":       "cluster deployment instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_deployment_status_replicas_available":        "cluster deployment instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_deployment_status_replicas_updated":          "cluster deployment instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"kube_namespace_status_phase":                      "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version phase",
	"kube_node_created":                                "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version",
	"kube_node_info":                                   "cluster container_runtime_version instance internal_ip job k8s_cluster_name kernel_version kubelet_version kubeproxy_version node os_image otel_scope_name otel_scope_version pod_cidr provider_id",
	"kube_node_role":                                   "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version role",
	"kube_node_spec_pod_cidrs":                         "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version pod_cidr",
	"kube_node_spec_unschedulable":                     "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version",
	"kube_node_status_addresses":                       "address cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version type",
	"kube_node_status_allocatable":                     "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version resource unit",
	"kube_node_status_capacity":                        "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version resource unit",
	"kube_node_status_condition":                       "cluster condition instance job k8s_cluster_name node otel_scope_name otel_scope_version status",
	"kube_pod_container_info":                          "cluster container container_id image image_id image_spec instance job k8s_cluster_name namespace otel_scope_name otel_scope_version pod uid",
	"kube_pod_container_resource_limits":               "cluster container instance job k8s_cluster_name namespace node otel_scope_name otel_scope_version pod resource uid unit",
	"kube_pod_container_resource_requests":             "cluster container instance job k8s_cluster_name namespace node otel_scope_name otel_scope_version pod resource uid unit",
	"kube_pod_container_status_restarts_total":         "cluster container instance job k8s_cluster_name namespace otel_scope_name otel_scope_version pod uid",
	"kube_pod_info":                                    "cluster created_by_kind created_by_name host_ip host_network instance job k8s_cluster_name namespace node otel_scope_name otel_scope_version pod pod_ip priority_class uid",
	"kube_pod_owner":                                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version owner_is_controller owner_kind owner_name pod uid",
	"kube_pod_start_time":                              "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version pod uid",
	"kube_pod_status_phase":                            "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version phase pod uid",
	"kube_replicaset_created":                          "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_metadata_generation":              "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_owner":                            "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version owner_is_controller owner_kind owner_name replicaset",
	"kube_replicaset_spec_replicas":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_status_fully_labeled_replicas":    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_status_observed_generation":       "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_status_ready_replicas":            "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_status_replicas":                  "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_replicaset_status_terminating_replicas":      "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version replicaset",
	"kube_secret_metadata_resource_version":            "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version secret",
	"kubelet_cgroup_manager_duration_seconds":          "cluster instance job k8s_cluster_name le operation_type otel_scope_name otel_scope_version",
	"kubelet_node_name":                                "cluster instance job k8s_cluster_name node otel_scope_name otel_scope_version",
	"kubelet_pleg_relist_duration_seconds":             "cluster instance job k8s_cluster_name le otel_scope_name otel_scope_version",
	"kubelet_pod_start_duration_seconds":               "cluster instance job k8s_cluster_name le otel_scope_name otel_scope_version",
	"kubelet_pod_worker_duration_seconds":              "cluster instance job k8s_cluster_name le operation_type otel_scope_name otel_scope_version",
	"kubelet_running_containers":                       "cluster container_state instance job k8s_cluster_name otel_scope_name otel_scope_version",
	"kubelet_running_pods":                             "cluster instance job k8s_cluster_name otel_scope_name otel_scope_version",
	"kubelet_runtime_operations_errors_total":          "cluster instance job k8s_cluster_name operation_type otel_scope_name otel_scope_version",
	"kubelet_runtime_operations_total":                 "cluster instance job k8s_cluster_name operation_type otel_scope_name otel_scope_version",
	"kubernetes_build_info":                            "build_date cluster compiler git_commit git_tree_state git_version go_version instance job k8s_cluster_name major minor otel_scope_name otel_scope_version platform",
	"machine_memory_bytes":                             "boot_id cluster instance job k8s_cluster_name otel_scope_name otel_scope_version",
	"node_cpu_frequency_max_hertz":                     "cluster cpu instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_frequency_min_hertz":                     "cluster cpu instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_guest_seconds_total":                     "cluster cpu instance job k8s_cluster_name mode namespace otel_scope_name otel_scope_version",
	"node_cpu_isolated":                                "cluster cpu instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_scaling_frequency_hertz":                 "cluster cpu instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_scaling_frequency_max_hertz":             "cluster cpu instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_scaling_frequency_min_hertz":             "cluster cpu instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_scaling_governor":                        "cluster cpu governor instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_cpu_seconds_total":                           "cluster cpu instance job k8s_cluster_name mode namespace otel_scope_name otel_scope_version",
	"node_exporter_build_info":                         "branch cluster goarch goos goversion instance job k8s_cluster_name namespace otel_scope_name otel_scope_version revision tags version",
	"node_filesystem_avail_bytes":                      "cluster device fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_device_error":                     "cluster device device_error fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_files":                            "cluster device fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_files_free":                       "cluster device fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_free_bytes":                       "cluster device fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_mount_info":                       "cluster device instance job k8s_cluster_name major minor mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_purgeable_bytes":                  "cluster device fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_readonly":                         "cluster device device_error fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_filesystem_size_bytes":                       "cluster device fstype instance job k8s_cluster_name mountpoint namespace otel_scope_name otel_scope_version",
	"node_memory_Active_anon_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Active_bytes":                         "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Active_file_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_AnonHugePages_bytes":                  "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_AnonPages_bytes":                      "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Bounce_bytes":                         "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Buffers_bytes":                        "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Cached_bytes":                         "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_CommitLimit_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Committed_AS_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Dirty_bytes":                          "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Inactive_anon_bytes":                  "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Inactive_bytes":                       "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Inactive_file_bytes":                  "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_KernelStack_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Mapped_bytes":                         "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_MemAvailable_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_MemFree_bytes":                        "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_MemTotal_bytes":                       "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Mlocked_bytes":                        "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_NFS_Unstable_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_PageTables_bytes":                     "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Percpu_bytes":                         "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_SReclaimable_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_SUnreclaim_bytes":                     "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_ShmemHugePages_bytes":                 "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_ShmemPmdMapped_bytes":                 "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Shmem_bytes":                          "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Slab_bytes":                           "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_SwapCached_bytes":                     "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_SwapFree_bytes":                       "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_SwapTotal_bytes":                      "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Unevictable_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_VmallocChunk_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_VmallocTotal_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_VmallocUsed_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_WritebackTmp_bytes":                   "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_memory_Writeback_bytes":                      "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_network_receive_bytes_total":                 "cluster device instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_network_receive_drop_total":                  "cluster device instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_network_transmit_bytes_total":                "cluster device instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"node_network_transmit_drop_total":                 "cluster device instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"process_cpu_seconds_total":                        "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"process_resident_memory_bytes":                    "cluster instance job k8s_cluster_name namespace otel_scope_name otel_scope_version",
	"rest_client_requests_total":                       "cluster code host instance job k8s_cluster_name method otel_scope_name otel_scope_version",
	"storage_operation_duration_seconds":               "cluster instance job k8s_cluster_name le migrated operation_name otel_scope_name otel_scope_version status volume_plugin",
	"target_info":                                      "cluster instance job k8s_cluster_name k8s_container_name k8s_daemonset_name k8s_namespace_name k8s_node_name k8s_pod_name k8s_pod_uid k8s_replicaset_name server_address server_port url_scheme",
	"volume_manager_total_volumes":                     "cluster instance job k8s_cluster_name otel_scope_name otel_scope_version plugin_name state",
}
